let naam = "Skyler";
let level = 3;
let strenght = 15;
let speed = 4;
let lives = 2;
let powers = "gravity control"
let weapon = "bat"
let charisma = 1;
let intelligence = 12;
let respawn = true;
console.log("Name: " + naam);
console.log("Level: " + level);
console.log("Strenght: " + strenght);
console.log("Speed: " + speed);
console.log("Lives: " + lives);
console.log("Powers: " + powers);
console.log("Weapon :" + weapon);
console.log("Charisma: " + charisma);
console.log("Intelligence: " + intelligence);
console.log("Respawn: " + respawn);